//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLuceneDbStore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestLuceneDbStore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* 
        /// * Licensed to the Apache Software Foundation (ASF) under one or more
        /// * contributor license agreements.  See the NOTICE file distributed with
        /// * this work for additional information regarding copyright ownership.
        /// * The ASF licenses this file to You under the Apache License, Version 2.0
        /// * (the &quot;License&quot;); you may not use this file except in compliance with
        /// * the License.  You may obtain a copy of the License at
        /// * 
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// * 
        /// * Unless required by appl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexReader {
            get {
                return ResourceManager.GetString("IndexReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* 
        /// * Licensed to the Apache Software Foundation (ASF) under one or more
        /// * contributor license agreements.  See the NOTICE file distributed with
        /// * this work for additional information regarding copyright ownership.
        /// * The ASF licenses this file to You under the Apache License, Version 2.0
        /// * (the &quot;License&quot;); you may not use this file except in compliance with
        /// * the License.  You may obtain a copy of the License at
        /// * 
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// * 
        /// * Unless required by appl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexWriter {
            get {
                return ResourceManager.GetString("IndexWriter", resourceCulture);
            }
        }
    }
}
